# fly.toml file generated for movie-together on 2022-01-15T22:02:34+01:00

app = "movie-together"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "3000"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[deploy]
  release_command = "npx prisma migrate deploy"

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
